name: "NPM Package Version Bump"
description: "Bumps version of NPM package"
inputs:
  workDir:
    description: "Directory containing `package.json` file"
    required: false
    default: "."
  isPrerelease:
    description: "Should bump version for prerelease"
    required: false
    default: "true"
  preid:
    description: "Prerelease version ID"
    required: false
    default: "pre"
outputs:
  version:
    description: "Resolved new version"
runs:
  using: "node12"
  main: "dist/index.js"
