name: "main"
on:
  pull_request:
  push:
    # branches:
    #   - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: |
          # FIXME: Using github's function `hashFiles` seemed to give incorrect
          # results for the directory so we're using md5sum instead.
          echo "CURRENT_HASH=$(find dist -type f -exec md5sum {} \; | md5sum)" >> $GITHUB_ENV

      - run: |
          rm -rf dist
          yarn run prepare

          EXPECTED_HASH=$(find dist -type f -exec md5sum {} \; | md5sum)

          echo "CURRENT_HASH: ${{ env.CURRENT_HASH }}"
          echo "EXPECTED_HASH: $EXPECTED_HASH"

          RESULT=$(expr "${{ env.CURRENT_HASH }}" != "$EXPECTED_HASH")
          exit $RESULT
